version: "2"
services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - 3000:3000
    restart: "${RESTART}"
    network_mode: bridge
    
volumes:
  grafana-data:
    driver: local
