version: "2"
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - prometheus:/etc/prometheus
    ports:
      - 9090:9090
    restart: "${RESTART}"
    network_mode: bridge
    
volumes:
  prometheus:
    driver: local
