.catalog:
  name: grafana
  version: 6.2.5
  uuid: grafana-625
  questions:
  - variable: RESTART
    description: 'Application restart option: no, always, on-failure'
    label: 'Restart:'
    required: true
    default: "always"
    type: string
