version: '2'
services:
  otrs:
    image: juanluisbaptiste/otrs:latest
    ports:
    - "8010:8010"
    links:
    - mariadb:mariadb
    - postfix:postfix
    volumes_from:
    - data
    environment:
        MYSQL_ROOT_PASSWORD: changeme
        OTRS_ROOT_PASSWORD: changeme
        OTRS_NUMBER_GENERATOR: Date
        OTRS_LANGUAGE: es
        OTRS_POSTMASTER_FETCH_TIME: 5

  mariadb:
    image: juanluisbaptiste/otrs-mariadb:latest
    expose:
    - "3306"
    volumes_from:
    - data
    environment:
        MYSQL_ROOT_PASSWORD: changeme

  postfix:
     image: juanluisbaptiste/postfix:latest
     expose:
     - "25"
     environment:
       SMTP_SERVER=smtp.yourcompany.com
       SMTP_USERNAME=otrs@yourcompany.com
       SMTP_PASSWORD=xxxxxxx
       SERVER_HOSTNAME=support.yourcompany.com

#  nginx:
#   image: juanluisbaptiste/bigbluebutton-proxy
#    ports:
#      - "80:80"
#      - "443:443"
#    volumes:
#     - /var/run/docker.sock:/tmp/docker.sock
#      - "/etc/localtime:/etc/localtime:ro"

  data:
    image: centos/mariadb:latest
    volumes:
    - /var/lib/mysql
    - "./otrs/backup:/var/otrs/backups"

    command: /bin/true
